# Data Loading, Cleaning & Export

### Importazione Librerie

In [1]:
import numpy as np
import pandas as pd
import requests

### Caricamento Dati

In [42]:
CSV_files = {
    "customers":           r"output/customers.csv",
    "geolocation_dataset": r"output/geolocation_dataset.csv",
    "order_items":         r"output/orders_items.csv",
    "order_payments":      r"dataset/olist_order_payments_dataset.csv",
    "order_review":        r"output/order_review.csv",
    "order_dataset":       r"output/order_dataset.csv",
    "list_product":        r"dataset/olist_products_dataset.csv",
    "list_seller":         r"output/list_seller.csv"
}
dataframes = {name: pd.read_csv(path) for name, path in CSV_files.items()}

df_customers           = dataframes["customers"]
df_orders_items        = dataframes["order_items"]
df_order_payments      = dataframes["order_payments"]
df_order_review        = dataframes["order_review"]
df_order_dataset       = dataframes["order_dataset"]
df_list_product        = dataframes["list_product"]
df_list_seller         = dataframes["list_seller"]
df_geolocation_dataset = dataframes["geolocation_dataset"]

### Regressione Lineare Multivariata

In [43]:
df_customers          
     

df_order_review     
          

df_order_payments      
  
order_it=df_orders_items.drop(['eur_price','eur_freight_value','shipping_limit_date','seller_id'],axis=1)
 
df_order_dataset

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,actual_delivery_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,13.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,9.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,2.0
...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,-11.0,8.0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,-2.0,22.0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,-6.0,24.0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,-21.0,17.0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,-18.0,7.0

In [44]:
product=df_list_product.drop(['product_name_lenght','product_description_lenght','product_photos_qty','product_category_name'],axis=1)

In [45]:
order_product=order_it.merge(product, on='product_id')
order_product=order_product.dropna()
order_product.info()

<class 'pandas.DataFrame'>
Index: 112632 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           112632 non-null  str
 1   order_item_id      112632 non-null  int64
 2   product_id         112632 non-null  str
 3   product_weight_g   112632 non-null  float64
 4   product_length_cm  112632 non-null  float64
 5   product_height_cm  112632 non-null  float64
 6   product_width_cm   112632 non-null  float64
dtypes: float64(4), int64(1), str(2)
memory usage: 6.9 MB

In [46]:
order_product=order_product.drop(['product_id','order_item_id'],axis=1)

In [47]:
order_pp=order_product.merge(df_order_payments, on='order_id')
order_pp

,order_id,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value
0,00010242fe8c5a6d1ba2dd792cb16214,650.0,28.0,9.0,14.0,1,credit_card,2,72.19
1,00018f77f2f0320c557190d7a144bdd3,30000.0,50.0,30.0,40.0,1,credit_card,3,259.83
2,000229ec398224ef6ca0657da4fc703e,3050.0,33.0,13.0,33.0,1,credit_card,5,216.87
3,00024acbcdf0a6daa1e931b038114c75,200.0,16.0,10.0,15.0,1,credit_card,2,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,3750.0,35.0,40.0,30.0,1,credit_card,3,218.04
...,...,...,...,...,...,...,...,...,...
117576,fffc94f6ce00a00581880bf54a75a037,10150.0,89.0,15.0,40.0,1,boleto,1,343.40
117577,fffcd46ef2263f404302a634eb57f7eb,8950.0,45.0,26.0,38.0,1,boleto,1,386.53
117578,fffce4705a9662cd70adb13d4a31832d,967.0,21.0,24.0,19.0,1,credit_card,3,116.85
117579,fffe18544ffabc95dfada21779c9644f,100.0,20.0,20.0,20.0,1,credit_card,3,64.71
117580,fffe41c64501cc87c801fd61db3f6244,600.0,30.0,3.0,19.0,1,credit_card,1,55.79

In [48]:
df_order_dataset=df_order_dataset[df_order_dataset['order_status']=='delivered']#filtarer solo i consegnati

In [49]:
df_order_dataset=df_order_dataset.drop(['order_status','customer_id'],axis=1)

In [50]:
df=order_pp.merge(df_order_dataset, on='order_id')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115015 entries, 0 to 115014
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115015 non-null  str
 1   product_weight_g               115015 non-null  float64
 2   product_length_cm              115015 non-null  float64
 3   product_height_cm              115015 non-null  float64
 4   product_width_cm               115015 non-null  float64
 5   payment_sequential             115015 non-null  int64
 6   payment_type                   115015 non-null  str
 7   payment_installments           115015 non-null  int64
 8   payment_value                  115015 non-null  float64
 9   order_purchase_timestamp       115015 non-null  str
 10  order_approved_at              115000 non-null  str
 11  order_delivered_carrier_date   115013 non-null  str
 12  order_delivered_customer_date  115007 non-null  str
 13  order_estimated_delivery_date  115015 non-null  str
 14  delivery_delay_days            115007 non-null  float64
 15  actual_delivery_days           115007 non-null  float64
dtypes: float64(7), int64(2), str(7)
memory usage: 14.0 MB

In [51]:

date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')  # 'coerce' trasforma valori non validi in NaN

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115015 entries, 0 to 115014
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115015 non-null  str
 1   product_weight_g               115015 non-null  float64
 2   product_length_cm              115015 non-null  float64
 3   product_height_cm              115015 non-null  float64
 4   product_width_cm               115015 non-null  float64
 5   payment_sequential             115015 non-null  int64
 6   payment_type                   115015 non-null  str
 7   payment_installments           115015 non-null  int64
 8   payment_value                  115015 non-null  float64
 9   order_purchase_timestamp       115015 non-null  datetime64[us]
 10  order_approved_at              115000 non-null  datetime64[us]
 11  order_delivered_carrier_date   115013 non-null  datetime64[us]
 12  order_delivered_customer_date  115007 non-null  datetime64[us]
 13  order_estimated_delivery_date  115015 non-null  datetime64[us]
 14  delivery_delay_days            115007 non-null  float64
 15  actual_delivery_days           115007 non-null  float64
dtypes: datetime64[us](5), float64(7), int64(2), str(2)
memory usage: 14.0 MB

In [53]:
df['actual_delivery_days'] = (
    df['order_delivered_customer_date'] - df['order_purchase_timestamp']
).dt.days

In [54]:
# tempo di approvazione
df['approval_time_days'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.days

# tempo spedizione dal corriere al cliente
df['shipping_time_days'] = (df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.days

# mese e giorno settimana dell'acquisto
df['purchase_month'] = df['order_purchase_timestamp'].dt.month
df['purchase_weekday'] = df['order_purchase_timestamp'].dt.weekday

In [55]:
df = pd.get_dummies(df, columns=['payment_type'], drop_first=True, dtype=int)

In [56]:
df = df.dropna(subset=['actual_delivery_days', 'approval_time_days', 'shipping_time_days'])

In [57]:
df.info()

<class 'pandas.DataFrame'>
Index: 114991 entries, 0 to 115014
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       114991 non-null  str
 1   product_weight_g               114991 non-null  float64
 2   product_length_cm              114991 non-null  float64
 3   product_height_cm              114991 non-null  float64
 4   product_width_cm               114991 non-null  float64
 5   payment_sequential             114991 non-null  int64
 6   payment_installments           114991 non-null  int64
 7   payment_value                  114991 non-null  float64
 8   order_purchase_timestamp       114991 non-null  datetime64[us]
 9   order_approved_at              114991 non-null  datetime64[us]
 10  order_delivered_carrier_date   114991 non-null  datetime64[us]
 11  order_delivered_customer_date  114991 non-null  datetime64[us]
 12  order_estimated_delivery_date  114991 non-null  datetime64[us]
 13  delivery_delay_days            114991 non-null  float64
 14  actual_delivery_days           114991 non-null  float64
 15  approval_time_days             114991 non-null  float64
 16  shipping_time_days             114991 non-null  float64
 17  purchase_month                 114991 non-null  int32
 18  purchase_weekday               114991 non-null  int32
 19  payment_type_credit_card       114991 non-null  int64
 20  payment_type_debit_card        114991 non-null  int64
 21  payment_type_voucher           114991 non-null  int64
dtypes: datetime64[us](5), float64(9), int32(2), int64(5), str(1)
memory usage: 19.3 MB

In [58]:
features = [
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm',
    'payment_sequential',
    'payment_installments',
    
] + [col for col in df.columns if col.startswith('payment_type_')]

In [59]:
y = df['actual_delivery_days']
X = df[features]

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

print("R²:", model.score(X_test, y_test))

R²: 0.015378555995066212